//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authordatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_table
    {
        public int author_id { get; set; }
        public string author_name { get; set; }
        public string author_publisher { get; set; }
    }
}
