//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authordatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookuser
    {
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string user_publisher { get; set; }
        public string user_password { get; set; }
    }
}
