//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authordatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookassign
    {
        public Nullable<int> book_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> book_assigned { get; set; }
        public int id { get; set; }
    }
}
